// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/tools/list-workspaces.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/toolError.ts
function throwToolError(tool, error) {
  const detail = error && typeof error === "object" && "message" in error ? String(error.message) : String(error);
  console.error(JSON.stringify({ level: "error", event: "mcp_tool_error", tool, detail }));
  throw new Error(`The ${tool} tool could not complete the request.`);
}

// src/lib/mcp/rateLimit.ts
var DEFAULT_MAX_REQUESTS = 60;
async function enforceMcpRateLimit(supabase, toolName, maxRequests = DEFAULT_MAX_REQUESTS) {
  const { data: userData, error: userError } = await supabase.auth.getUser();
  if (userError || !userData?.user) throwToolError(toolName, userError ?? new Error("no user"));
  const { data, error } = await supabase.rpc("check_ai_rate_limit", {
    _user_id: userData.user.id,
    _workspace_id: null,
    _function_name: `mcp_${toolName}`,
    _max_requests: maxRequests
  });
  if (error) throwToolError(toolName, error);
  if (data !== true) {
    throw new Error(`Rate limit reached for ${toolName}. Try again later.`);
  }
}

// src/lib/mcp/tools/list-workspaces.ts
var list_workspaces_default = defineTool({
  name: "list_workspaces",
  title: "List workspaces",
  description: "List the startup workspaces the signed-in user can access, with stage, health score and program.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(25).describe("Maximum workspaces to return."),
    search: z.string().trim().optional().describe("Optional startup name filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    await enforceMcpRateLimit(supabase, "list_workspaces");
    let query = supabase.from("workspaces").select(
      "id, stage, health_score, priority_level, updated_at, startup:startups!inner(id, name), program:programs(id, name, program_type)"
    ).order("updated_at", { ascending: false });
    if (search) query = query.ilike("startup.name", `%${search}%`);
    const { data, error } = await query.limit(limit ?? 25);
    if (error) throwToolError("list_workspaces", error);
    const rows = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { workspaces: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/tools/get-workspace-overview.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z2 } from "npm:zod@^3.25.76";
var get_workspace_overview_default = defineTool2({
  name: "get_workspace_overview",
  title: "Get workspace overview",
  description: "Get one workspace with its startup, program, milestones and open action items. Use list_workspaces to find the id.",
  inputSchema: {
    workspace_id: z2.string().uuid().describe("Workspace id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ workspace_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    await enforceMcpRateLimit(supabase, "get_workspace_overview");
    const [workspace, milestones, actions] = await Promise.all([
      supabase.from("workspaces").select(
        "id, stage, health_score, health_notes, priority_level, current_week, updated_at, startup:startups(id, name, description, website), program:programs(id, name, program_type)"
      ).eq("id", workspace_id).maybeSingle(),
      supabase.from("milestones").select("id, title, status, target_date, position").eq("workspace_id", workspace_id).order("position", { ascending: true }),
      supabase.from("action_items").select("id, title, status, priority, due_date").eq("workspace_id", workspace_id).neq("status", "completed").order("due_date", { ascending: true, nullsFirst: false }).limit(50)
    ]);
    const failure = workspace.error ?? milestones.error ?? actions.error;
    if (failure) throwToolError("get_workspace_overview", failure);
    if (!workspace.data) {
      return { content: [{ type: "text", text: "Workspace not found or not accessible" }], isError: true };
    }
    const payload = {
      workspace: workspace.data,
      milestones: milestones.data ?? [],
      open_actions: actions.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-action-items.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z3 } from "npm:zod@^3.25.76";
var list_action_items_default = defineTool3({
  name: "list_action_items",
  title: "List action items",
  description: "List action items across accessible workspaces. Optionally filter by workspace, status, or only overdue items.",
  inputSchema: {
    workspace_id: z3.string().uuid().optional().describe("Restrict to a single workspace."),
    status: z3.enum(["pending", "in_progress", "awaiting_validation", "completed", "cancelled"]).optional().describe("Filter by action status."),
    only_overdue: z3.boolean().default(false).describe("Only items past their due date and not completed."),
    limit: z3.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ workspace_id, status, only_overdue, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    await enforceMcpRateLimit(supabase, "list_action_items");
    let query = supabase.from("action_items").select("id, workspace_id, title, description, status, priority, due_date, created_at").order("due_date", { ascending: true, nullsFirst: false }).limit(limit ?? 25);
    if (workspace_id) query = query.eq("workspace_id", workspace_id);
    if (status) query = query.eq("status", status);
    if (only_overdue) {
      query = query.lt("due_date", (/* @__PURE__ */ new Date()).toISOString().slice(0, 10)).not("status", "in", "(completed,cancelled)");
    }
    const { data, error } = await query;
    if (error) throwToolError("list_action_items", error);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { action_items: data ?? [], count: (data ?? []).length }
    };
  }
});

// src/lib/mcp/tools/create-action-item.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z4 } from "npm:zod@^3.25.76";
var create_action_item_default = defineTool4({
  name: "create_action_item",
  title: "Create action item",
  description: "Create an action item inside a milestone of a workspace. Every action must belong to a milestone \u2014 use get_workspace_overview to pick one.",
  inputSchema: {
    workspace_id: z4.string().uuid().describe("Workspace the action belongs to."),
    milestone_id: z4.string().uuid().describe("Milestone the action belongs to."),
    title: z4.string().trim().min(1).max(200).describe("Short action title."),
    description: z4.string().trim().max(2e3).optional(),
    due_date: z4.string().trim().optional().describe("Due date as YYYY-MM-DD."),
    priority: z4.enum(["low", "medium", "high"]).default("medium")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ workspace_id, milestone_id, title, description, due_date, priority }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    await enforceMcpRateLimit(supabase, "create_action_item");
    const { data: ms, error: msError } = await supabase.from("milestones").select("id").eq("id", milestone_id).eq("workspace_id", workspace_id).maybeSingle();
    if (msError) throwToolError("create_action_item", msError);
    if (!ms) {
      return {
        content: [{ type: "text", text: "Milestone does not belong to this workspace" }],
        isError: true
      };
    }
    const { data, error } = await supabase.from("action_items").insert({
      workspace_id,
      milestone_id,
      title,
      description: description ?? null,
      due_date: due_date ?? null,
      priority: priority ?? "medium",
      status: "pending",
      created_by: ctx.getUserId()
    }).select("id, workspace_id, milestone_id, title, status, priority, due_date").maybeSingle();
    if (error) throwToolError("create_action_item", error);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { action_item: data }
    };
  }
});

// src/lib/mcp/tools/list-upcoming-sessions.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z5 } from "npm:zod@^3.25.76";
var list_upcoming_sessions_default = defineTool5({
  name: "list_upcoming_sessions",
  title: "List upcoming sessions",
  description: "List upcoming sessions (meetings) in the workspaces the signed-in user can access.",
  inputSchema: {
    workspace_id: z5.string().uuid().optional().describe("Restrict to a single workspace."),
    days_ahead: z5.number().int().min(1).max(90).default(30).describe("How far ahead to look, in days."),
    limit: z5.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ workspace_id, days_ahead, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    await enforceMcpRateLimit(supabase, "list_upcoming_sessions");
    const now = /* @__PURE__ */ new Date();
    const until = new Date(now.getTime() + (days_ahead ?? 30) * 864e5);
    let query = supabase.from("sessions").select("id, workspace_id, title, scheduled_at, duration, status").gte("scheduled_at", now.toISOString()).lte("scheduled_at", until.toISOString()).order("scheduled_at", { ascending: true }).limit(limit ?? 25);
    if (workspace_id) query = query.eq("workspace_id", workspace_id);
    const { data, error } = await query;
    if (error) throwToolError("list_upcoming_sessions", error);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { sessions: data ?? [], count: (data ?? []).length }
    };
  }
});

// src/lib/mcp/tools/list-crm-leads.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z6 } from "npm:zod@^3.25.76";
var list_crm_leads_default = defineTool6({
  name: "list_crm_leads",
  title: "List CRM leads",
  description: "List CRM pipeline leads (funnel items) the signed-in user can access, newest first. Optionally filter by stage or organisation name.",
  inputSchema: {
    stage: z6.string().trim().optional().describe("Funnel stage key to filter by."),
    search: z6.string().trim().optional().describe("Organisation name filter."),
    limit: z6.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ stage, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    await enforceMcpRateLimit(supabase, "list_crm_leads");
    let query = supabase.from("funnel_items").select("id, organization_name, stage, owner_consultant_id, last_activity_at, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (stage) query = query.eq("stage", stage);
    if (search) query = query.ilike("organization_name", `%${search}%`);
    const { data, error } = await query;
    if (error) throwToolError("list_crm_leads", error);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { leads: data ?? [], count: (data ?? []).length }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "apxzuslwhjujgrcsfzqw";
var mcp_default = defineMcp({
  name: "remix-of-startup-companion",
  title: "Remix of Startup Companion",
  version: "0.1.0",
  instructions: "Tools for the Startup Leiria companion platform. Read startup workspaces, milestones, action items, upcoming sessions and CRM leads, and create action items inside a milestone. All data is scoped to the signed-in user's permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_workspaces_default,
    get_workspace_overview_default,
    list_action_items_default,
    create_action_item_default,
    list_upcoming_sessions_default,
    list_crm_leads_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
