
GRANT EXECUTE ON FUNCTION public.has_workspace_access(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.has_workspace_access(uuid, uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.has_active_workspace_access(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.is_staff() TO anon;
GRANT EXECUTE ON FUNCTION public.is_admin() TO anon;
GRANT EXECUTE ON FUNCTION public.is_admin(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.is_admin_only() TO anon;
GRANT EXECUTE ON FUNCTION public.is_backoffice() TO anon;
GRANT EXECUTE ON FUNCTION public.is_founder_user() TO anon;
GRANT EXECUTE ON FUNCTION public.is_founder(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.is_startup_founder(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.is_external_mentor(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO anon;
GRANT EXECUTE ON FUNCTION public.has_any_role(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.is_account_active() TO anon;
GRANT EXECUTE ON FUNCTION public.is_account_active(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.can_access_backoffice() TO anon;
GRANT EXECUTE ON FUNCTION public.can_write_workspace(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.can_edit_workspace(uuid, uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.can_manage_startup(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.can_see_startup_pii(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.can_see_team_member_pii(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.is_conversation_participant(uuid, uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.is_connected_mentor(uuid, uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.is_team_member_of_startup(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.shares_workspace_with(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.has_program_access(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_workspace_role(uuid, uuid) TO anon;
